### ISSUE TITLE
Water sensor

### ISSUE THREAD

**Issue by Dr-know** [dupondje/homeassistant-dsmr#6]
Sorry to bother you again ;-).
In the next month i will need the water meter sensor also. (new digital water meter installed at parents ;-) )
i have read the documentation PDF[ e-MUCS_P1_Ed_1_7_1](https://github.com/FireWizard52/P1-Smart-meter/blob/main/e-MUCS_P1_Ed_1_7_1.pdf) this will be send also thru the electricity meter.

**Comment by dupondje** [comment]
The current code already handles a water meter.
Please let me know if it would'nt work :)
